### ISSUE TITLE
gobblet intermittent failure

### ISSUE THREAD

**Issue by samth** [racket/games#12]
The gobblet tests occasionally fail in DrDr: http://drdr.racket-lang.org/53847/racket/share/pkgs/games/gobblet/robot.rkt

This bug has existed for a *long* time and has resisted multiple prior fixes. Debugger beware.

racket/racket-ci#1

**Comment by samth** [comment]
So, now this times out occasionally, even with a very long timeout. http://drdr.racket-lang.org/54567/cs/racket/share/pkgs/games/gobblet/robot.rkt

**Comment by mflatt** [comment]
I pushed another attempt at a repair.

I think the timeout was because not posting the semaphore would always leave the search stuck.

**Comment by rfindler** [comment]
Looks like that fixed it? I've not seen any drdr failures in a while.

**Comment by samth** [comment]
Yes, I think this is fixed, finally.
