### ISSUE TITLE
internal error: attempt to deschedule the current thread in atomic mode

### ISSUE THREAD

**Issue by AiziChen** [racket/games#16]
System Information:
`Linux raspberrypi 5.10.60-v8+ aarch64 GNU/Linux`

Racket Version:
`Racket v8.2.0.8 [cs].`

Errors:
```
internal error: attempt to deschedule the current thread in atomic mode
  context...:
   /home/pi/racket/racket/collects/racket/private/more-scheme.rkt:148:2: call-with-break-parameterization
   /home/pi/racket/racket/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:370:11: eventspace-handler-thread-proc
```
these errors will be repeated over and over.

Expect `Jewel` `Checkers` and `Gobblet`, other games will not have these problems.

[video to display](https://vimeo.com/607072183)

**Comment by mflatt** [comment]
Thanks for the report! Can you tell me more about which distribution you're running? I tried with an Ubuntu aarch64 distro (on a Pi 4B), and I was not able to trigger the crash.

**Comment by mflatt** [comment]
One more idea: I you redirect stderr to a file in tmp, is the first error message the same? The "deschedule" error could be just fallout from the original error.

**Comment by AiziChen** [comment]
This is the previous error:
```
internal error: attempt to deschedule the current thread in atomic mode
  context...:
   /home/pi/Downloads/racket/racket/share/pkgs/gui-lib/mred/private/messagebox.rkt:26:2: do-message-box/custom
   /home/pi/Downloads/racket/racket/share/pkgs/gui-lib/mred/private/messagebox.rkt:302:2: do-message-box
   /home/pi/Downloads/racket/racket/collects/racket/private/more-scheme.rkt:163:2: select-handler/no-breaks
   /home/pi/Downloads/racket/racket/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:435:6
   /home/pi/Downloads/racket/racket/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:486:32
   /home/pi/Downloads/racket/racket/collects/racket/private/more-scheme.rkt:148:2: call-with-break-parameterization
   /home/pi/Downloads/racket/racket/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:370:11: eventspace-handler-thread-proc
get-glx-version: need GLX version 1.3 or greater; given version 1.2
  context...:
   /home/pi/Downloads/racket/racket/collects/racket/private/promise.rkt:103:0: force/generic
   /home/pi/Downloads/racket/racket/share/pkgs/gui-lib/mred/private/wx/gtk/gl-context.rkt:352:0: make-gtk-drawable-gl-context
   /home/pi/Downloads/racket/racket/share/pkgs/gui-lib/mred/private/wx/gtk/gl-context.rkt:465:0: make-gtk-widget-gl-context
   /home/pi/Downloads/racket/racket/share/pkgs/gui-lib/mred/private/wx/gtk/dc.rkt:190:4: get-gl-context method in dc%
   .../private/arrow-higher-order.rkt:379:33
   /home/pi/Downloads/racket/racket/share/pkgs/games/jewel/jewel.rkt:196:2
   /home/pi/Downloads/racket/racket/collects/racket/private/class-internal.rkt:3608:0: continue-make-object
   /home/pi/Downloads/racket/racket/collects/racket/private/class-internal.rkt:3582:0: do-make-object/real-class
   .../racket/unit.rkt:1010:20
   /home/pi/Downloads/racket/racket/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:435:6
   /home/pi/Downloads/racket/racket/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:486:32
   /home/pi/Downloads/racket/racket/collects/racket/private/more-scheme.rkt:148:2: call-with-break-parameterization
   /home/pi/Downloads/racket/racket/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:370:11: eventspace-handler-thread-proc
internal error: tried to deschedule a descheduled thread
  context...:
   /home/pi/Downloads/racket/racket/collects/racket/private/more-scheme.rkt:148:2: call-with-break-parameterization
   /home/pi/Downloads/racket/racket/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:370:11: eventspace-handler-thread-proc
internal error: attempt to deschedule the current thread in atomic mode
  context...:
   /home/pi/Downloads/racket/racket/collects/racket/private/more-scheme.rkt:148:2: call-with-break-parameterization
```
It seems to be a problem with the GLX version.

**Comment by AiziChen** [comment]
The Linux version I use is raspberrypi aarch64. There is no official version, but it is suitable for 8GB raspberrypi 4B.

**Comment by AiziChen** [comment]
According to the above error message, GLX1.2 needs to be upgraded to 1.3, but I don’t know how to upgrade it😆

**Comment by AiziChen** [comment]
According to the above error message, GLX1.2 needs to be upgraded to 1.3, but I don’t know how to upgrade it😆

**Comment by mflatt** [comment]
Thanks for the information! I will work on the way the GLX error is reported, since raising an error in an atomic region is not a good way of handling the error. Maybe I can also do something about the "attempt to deschedule" error, instead of having Racket complain forever. GLX1.3 is not particularly new, so it's puzzling to me that any aarch64 installation would have 1.2, but I don't know all that much about it.

**Comment by mflatt** [comment]
I finally got back to this, and I pushed a commit (5bab880266 in racket/racket) aimed at the neverending-errors problem.

I haven't been able to replicate the GL problem, though. I started with a Raspberry Pi Buster installation (http://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2021-05-28/), and after `apt upgrade` and reboot, `uname -a` shows `Linux raspberrypi 5.10.63-v8+ ...`. I installed the `libglu1-mesa` package, and then GL games like Jewel and Gobblet ran ok. Do you know what might have been different in your installation?

**Comment by AiziChen** [comment]
I sold my raspberry pi, so I can't test it now. It may be that I did not install the `libglu1-mesa` package or somthing. thank you! I will close this issue.
