### ISSUE TITLE
make-card does not assign correct width and height

### ISSUE THREAD

**Issue by alexzandros** [racket/games#5]
I'm trying to create a card game, and when I instance the card interface on top of a table I notice the card size is always 71x96 no matter what are the size of the bitmaps used for front and back.

My code is as follows
```racket
#lang racket
(require games/cards racket/gui)

(define bm (make-object bitmap%
             (build-path "C:\\Users\\carlos\\Pictures\\cardGame\\" "evento_0001.png")))
(define fondo (make-object bitmap%
             (build-path "C:\\Users\\carlos\\Pictures\\cardGame\\" "fondo.png")))
(define cartita (make-card bm fondo 'Eventos '|Mama Perruna|))
(send cartita flip)
(define mesa (make-table "Juego" 18 7))
(send mesa add-region (make-button-region 110 0 100 50 "El boton" (λ ()(send cartita flip))))
(send mesa add-card cartita 100 60)
(send mesa show #t)
```
The dimensions of both bitmaps are 200x279 as can be seen in the screenshot
![image](https://user-images.githubusercontent.com/10458935/29461270-b702e24c-83f0-11e7-90e5-463ad1638d04.png)
The next screenshot shows how it looks when I try to drag the card
![image](https://user-images.githubusercontent.com/10458935/29461224-85a9238c-83f0-11e7-9a36-42e67f7fa669.png)

**Comment by mflatt** [comment]
Repair merged.
